# Generated by Django 4.0.3 on 2022-07-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencies', models.CharField(db_index=True, max_length=50, verbose_name='Валюты')),
            ],
            options={
                'verbose_name': 'название валюты',
                'verbose_name_plural': 'название валют',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sume', models.CharField(max_length=10, verbose_name='Сумма обмена')),
                ('curr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange_app.currencies', verbose_name='Валюта покупки(продажи)')),
            ],
            options={
                'verbose_name': 'конвертируем валюту',
                'verbose_name_plural': 'конвертируем валюту',
            },
        ),
    ]
